# .github/workflows/test-database.yml
name: Test Database Workflow

on:
  workflow_call:
    inputs:
      database:
        required: true
        type: string
      database-config:
        required: false
        type: string

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        supported_ruby_version: ['3.1', '3.2', '3.3']

    runs-on: ubuntu-latest

    services:
      db:
        image: ${{ fromJson(inputs.database-config).image }}
        env: ${{ fromJson(inputs.database-config).env }}
        ports: ${{ fromJson(inputs.database-config).ports }}
        options: ${{ fromJson(inputs.database-config).options }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

    - name: Install dependencies and configure environment
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          build-essential \
          bzr git mercurial subversion cvs \
          ghostscript \
          gsfonts \
          imagemagick libmagick++-dev \
          libnss3-dev locales
        sudo locale-gen en_US # for bazaar non ascii test
        sudo sed -ri 's/(rights)="none" (pattern="PDF")/\1="read" \2/' /etc/ImageMagick-6/policy.xml # Configure ImageMagick for PDF support

    - name: Create config/database.yml
      shell: bash
      run: |
        cat > config/database.yml <<EOF
        test:
          adapter: ${{ inputs.database }}
          database: testdb
          username: user
          password: password
          host: 127.0.0.1
        EOF

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.supported_ruby_version }}
        bundler-cache: true 

    - name: Prepare Test Environment
      shell: bash
      run: |
        SCMS=subversion,git,git_utf8,filesystem,bazaar,cvs bundle exec rake ci:about ci:setup db:environment:set RAILS_ENV=test

    - name: Run tests
      shell: bash
      run: |
        bundle exec rake test RAILS_ENV=test

    - name: Run bazaar non ascii test
      shell: bash
      run: |
        bundle exec rake test TEST=test/unit/repository_bazaar_test.rb RAILS_ENV=test
      env:
        LANG: en_US.ISO8859-1
        LC_ALL: en_US.ISO8859-1
