# .github/workflows/test-database.yml
name: Test Database Workflow

on:
  workflow_call:
    inputs:
      ruby-version:
        required: true
        type: string
      database:
        required: true
        type: string
      database-config:
        required: false
        type: string

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        supported_ruby_version: ['3.1', '3.2', '3.3']

    runs-on: ubuntu-latest

    services:
      db:
        image: ${{ fromJson(inputs.database-config).image }}
        env: ${{ fromJson(inputs.database-config).env }}
        ports: ${{ fromJson(inputs.database-config).ports }}
        options: ${{ fromJson(inputs.database-config).options }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ inputs.ruby-version }}

      - name: Configure Database
        run: echo "DATABASE_URL=${{ inputs.database-config.url }}" >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run Tests
        run: bundle exec rake test
