# .github/workflows/test-database.yml
name: Test Database Workflow

on:
  workflow_call:
    inputs:
      ruby-version:
        required: true
        type: string
      database:
        required: true
        type: string
      database-config:
        required: false
        type: object

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        name: ${{ inputs.database-config.name }}
        image: ${{ inputs.database-config.image }}
        env: ${{ inputs.database-config.env }}
        ports: ${{ inputs.database-config.ports }}
        options: ${{ inputs.database-config.options }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ inputs.ruby-version }}

      - name: Configure Database
        run: echo "DATABASE_URL=${{ inputs.database-config.url }}" >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run Tests
        run: bundle exec rake test
