# .github/workflows/main.yml
name: CI Test Workflow

on:
  push:
  workflow_dispatch:

jobs:
  test-postgresql:
    uses: ./.github/workflows/build_and_test_job.yml
    with:
      ruby-version: ${{ matrix.ruby-version }}
      database: postgresql
      database-config: >
        {
          "image": "postgres:13",
          "url": "postgres://postgres:password@localhost:5432/test_db",
          "env": {
            "POSTGRES_USER": "postgres",
            "POSTGRES_PASSWORD": "password"
          },
          "ports": ["5432:5432"],
          "options": "--health-cmd \"pg_isready -U user\" --health-interval 10s --health-timeout 5s --health-retries 5"
        }

  test-mysql:
    uses: ./.github/workflows/build_and_test_job.yml
    with:
      ruby-version: ${{ matrix.ruby-version }}
      database: mysql2
      database-config: >
        {
          "image": "mysql:8",
          "url": "mysql2://root:password@localhost:3306/test_db",
          "env": {
            "MYSQL_ROOT_PASSWORD": "password"
          },
          "ports": ["3306:3306"],
          "options": "--health-cmd=\"mysqladmin ping --silent\" --health-interval=10s --health-timeout=5s --health-retries=5"
        }

  test-sqlite:
    uses: ./.github/workflows/build_and_test_job.yml
    with:
      ruby-version: ${{ matrix.ruby-version }}
      database: sqlite3
      database-config: >
        {
          "url": "sqlite3:db/development.sqlite3"
        }
