name: Test

on:
  [push, workflow_dispatch]

jobs:
  setup_postgresql:
    strategy:
      fail-fast: false
      matrix:
        supported_ruby_version: ['3.1', '3.2', '3.3']
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        options: >-
          --health-cmd "pg_isready -U user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb

  build_and_test:
    needs: [setup_postgresql]
    uses: ./.github/workflows/build_and_test_job.yml
    with:
      supported_ruby_version: ${{ matrix.supported_ruby_version }}
      database: postgresql
