name: Test

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        supported_ruby_version: ['3.1', '3.2', '3.3']
        supported_database: ['postgresql', 'mysql2', 'sqlite3']

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        options: >-
          --health-cmd "pg_isready -U user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb

      mysql:
        image: mysql:8
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name mysql
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testdb
          MYSQL_USER: user
          MYSQL_PASSWORD: password

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.supported_ruby_version }}
          bundler-cache: true

      - uses: browser-actions/setup-chrome@v1

      - name: Update apt and install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            bzr git mercurial subversion cvs \
            ghostscript \
            gsfonts \
            imagemagick libmagick++-dev \
            libnss3-dev

      - name: Configure ImageMagick for PDF support
        run: |
          sudo sed -ri 's/(rights)="none" (pattern="PDF")/\1="read" \2/' /etc/ImageMagick-6/policy.xml

      - name: Configure DATABASE_URL
        run: |
          if [ "${{ matrix.supported_database }}" == "postgresql" ]; then
            echo "DATABASE_URL=postgresql://user:password@localhost/testdb" >> $GITHUB_ENV
          elif [ "${{ matrix.supported_database }}" == "mysql2" ]; then
            echo "DATABASE_URL=mysql2://127.0.0.1:3306/testdb" >> $GITHUB_ENV
          elif [ "${{ matrix.supported_database }}" == "sqlite3" ]; then
            echo "DATABASE_URL=sqlite3:tmp/testdb.sqlite3" >> $GITHUB_ENV
          fi

      - name: Stop Unused Services
        run: |
          if [ "${{ matrix.supported_database }}" != "postgresql" ]; then
            docker stop postgres || true
          fi
          if [ "${{ matrix.supported_database }}" != "mysql2" ]; then
            docker stop mysql || true
          fi

      - name: Install dependencies
        run: bundle install

      - name: Setup Redmine
        run: |
          # Disabled Mercurial due to installation difficulties. issue: https://www.redmine.org/issues/33784
          SCMS=subversion,git,filesystem,bazaar,cvs bundle exec rake ci:about ci:setup db:environment:set RAILS_ENV=test

      - name: Run Tests
        run: |
          bundle exec rake test RAILS_ENV=test

      - name: Run system tests
        run: bundle exec rake test:system RAILS_ENV=test
        env:
          GOOGLE_CHROME_OPTS_ARGS: "headless,disable-gpu,no-sandbox,disable-dev-shm-usage"
        if: always()

      - name: Store system test screenshots Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: system-test-screenshots
          path: tmp/screenshots
          if-no-files-found: ignore