name: Test

on:
  [push, workflow_dispatch]

env:
  SUPPORTED_RUBY_VERSIONS: '["3.1", "3.2", "3.3"]'

jobs:
  postgresql_test:
    strategy:
      fail-fast: false
      matrix:
        supported_ruby_version: ${{ fromJson(env.SUPPORTED_RUBY_VERSIONS) }}
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        options: >-
          --health-cmd "pg_isready -U user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build and Test
        uses: ./.github/workflows/build_and_test_steps
        with:
          supported_ruby_version: ${{ matrix.supported_ruby_version }}
          database: postgresql

  mysql2_test:
    strategy:
      fail-fast: false
      matrix:
        supported_ruby_version: ${{ fromJson(env.SUPPORTED_RUBY_VERSIONS) }}
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testdb
          MYSQL_USER: user
          MYSQL_PASSWORD: password
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build and Test
        uses: ./.github/workflows/build_and_test_steps
        with:
          supported_ruby_version: ${{ matrix.supported_ruby_version }}
          database: mysql2

  sqlite3_test:
    strategy:
      fail-fast: false
      matrix:
        supported_ruby_version: ${{ fromJson(env.SUPPORTED_RUBY_VERSIONS) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build and Test
        uses: ./.github/workflows/build_and_test_steps
        with:
          supported_ruby_version: ${{ matrix.supported_ruby_version }}
          database: sqlite3