name: Test with reusable workflow

on:
  push:
  workflow_dispatch:

jobs:
  postgresql:
    uses: ./.github/workflows/build_and_test_job.yml
    with:
      database_adapter: postgresql
      database_container_config: |
        {
          "image": "postgres:14",
          "env": {
            "POSTGRES_USER": "user",
            "POSTGRES_PASSWORD": "password",
            "POSTGRES_DB": "testdb"
          },
          "ports": ["5432:5432"],
          "options": "--health-cmd 'pg_isready -U user' --health-interval 10s --health-timeout 5s --health-retries 5"
        }

  mysql:
    uses: ./.github/workflows/build_and_test_job.yml
    with:
      database_adapter: mysql2
      database_container_config: |
        {
          "image": "mysql:8",
          "env": {
            "MYSQL_DATABASE": "testdb",
            "MYSQL_USER": "user",
            "MYSQL_PASSWORD": "password"
          },
          "ports": ["3306:3306"],
          "options": "--health-cmd='mysqladmin ping --silent' --health-interval=10s --health-timeout=5s --health-retries=5"
        }

  sqlite:
    uses: ./.github/workflows/build_and_test_job.yml
    with:
      database_adapter: sqlite3
