name: Test

on:
  [push, workflow_dispatch]

jobs:
  postgresql_test:
    strategy:
      fail-fast: false
      matrix:
        supported_ruby_version: ['3.1', '3.2', '3.3']

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        options: >-
          --health-cmd "pg_isready -U user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create config/database.yml
        run: |
          cat > config/database.yml <<EOF
          test:
            adapter: postgresql
            database: testdb
            username: user
            password: password
            host: 127.0.0.1
          EOF

      - name: Build and Test
        uses: ./github/workflows/build_and_test_steps.yml
